import type { MathSymbol } from '../../types/symbols';

export const SYMBOLS: MathSymbol[] = [
  // Greek lowercase
  { id: 'alpha', category: 'greek', label: 'alpha', latex: '\\alpha', display: 'α', keywords: ['alpha', 'greek'] },
  { id: 'beta', category: 'greek', label: 'beta', latex: '\\beta', display: 'β', keywords: ['beta', 'greek'] },
  { id: 'gamma', category: 'greek', label: 'gamma', latex: '\\gamma', display: 'γ', keywords: ['gamma', 'greek'] },
  { id: 'delta', category: 'greek', label: 'delta', latex: '\\delta', display: 'δ', keywords: ['delta', 'greek'] },
  { id: 'epsilon', category: 'greek', label: 'epsilon', latex: '\\epsilon', display: 'ε', keywords: ['epsilon', 'greek'] },
  { id: 'varepsilon', category: 'greek', label: 'varepsilon', latex: '\\varepsilon', display: 'ε', keywords: ['varepsilon', 'epsilon', 'greek'] },
  { id: 'zeta', category: 'greek', label: 'zeta', latex: '\\zeta', display: 'ζ', keywords: ['zeta', 'greek'] },
  { id: 'eta', category: 'greek', label: 'eta', latex: '\\eta', display: 'η', keywords: ['eta', 'greek'] },
  { id: 'theta', category: 'greek', label: 'theta', latex: '\\theta', display: 'θ', keywords: ['theta', 'greek'] },
  { id: 'vartheta', category: 'greek', label: 'vartheta', latex: '\\vartheta', display: 'ϑ', keywords: ['vartheta', 'theta', 'greek'] },
  { id: 'iota', category: 'greek', label: 'iota', latex: '\\iota', display: 'ι', keywords: ['iota', 'greek'] },
  { id: 'kappa', category: 'greek', label: 'kappa', latex: '\\kappa', display: 'κ', keywords: ['kappa', 'greek'] },
  { id: 'lambda', category: 'greek', label: 'lambda', latex: '\\lambda', display: 'λ', keywords: ['lambda', 'greek'] },
  { id: 'mu', category: 'greek', label: 'mu', latex: '\\mu', display: 'μ', keywords: ['mu', 'greek'] },
  { id: 'nu', category: 'greek', label: 'nu', latex: '\\nu', display: 'ν', keywords: ['nu', 'greek'] },
  { id: 'xi', category: 'greek', label: 'xi', latex: '\\xi', display: 'ξ', keywords: ['xi', 'greek'] },
  { id: 'pi', category: 'greek', label: 'pi', latex: '\\pi', display: 'π', keywords: ['pi', 'greek'] },
  { id: 'varpi', category: 'greek', label: 'varpi', latex: '\\varpi', display: 'ϖ', keywords: ['varpi', 'pi', 'greek'] },
  { id: 'rho', category: 'greek', label: 'rho', latex: '\\rho', display: 'ρ', keywords: ['rho', 'greek'] },
  { id: 'varrho', category: 'greek', label: 'varrho', latex: '\\varrho', display: 'ϱ', keywords: ['varrho', 'rho', 'greek'] },
  { id: 'sigma', category: 'greek', label: 'sigma', latex: '\\sigma', display: 'σ', keywords: ['sigma', 'greek'] },
  { id: 'varsigma', category: 'greek', label: 'varsigma', latex: '\\varsigma', display: 'ς', keywords: ['varsigma', 'sigma', 'greek'] },
  { id: 'tau', category: 'greek', label: 'tau', latex: '\\tau', display: 'τ', keywords: ['tau', 'greek'] },
  { id: 'upsilon', category: 'greek', label: 'upsilon', latex: '\\upsilon', display: 'υ', keywords: ['upsilon', 'greek'] },
  { id: 'phi', category: 'greek', label: 'phi', latex: '\\phi', display: 'φ', keywords: ['phi', 'greek'] },
  { id: 'varphi', category: 'greek', label: 'varphi', latex: '\\varphi', display: 'ϕ', keywords: ['varphi', 'phi', 'greek'] },
  { id: 'chi', category: 'greek', label: 'chi', latex: '\\chi', display: 'χ', keywords: ['chi', 'greek'] },
  { id: 'psi', category: 'greek', label: 'psi', latex: '\\psi', display: 'ψ', keywords: ['psi', 'greek'] },
  { id: 'omega', category: 'greek', label: 'omega', latex: '\\omega', display: 'ω', keywords: ['omega', 'greek'] },
  // Greek uppercase
  { id: 'Gamma', category: 'greek', label: 'Gamma', latex: '\\Gamma', display: 'Γ', keywords: ['Gamma', 'greek', 'uppercase'] },
  { id: 'Delta', category: 'greek', label: 'Delta', latex: '\\Delta', display: 'Δ', keywords: ['Delta', 'greek', 'uppercase'] },
  { id: 'Theta', category: 'greek', label: 'Theta', latex: '\\Theta', display: 'Θ', keywords: ['Theta', 'greek', 'uppercase'] },
  { id: 'Lambda', category: 'greek', label: 'Lambda', latex: '\\Lambda', display: 'Λ', keywords: ['Lambda', 'greek', 'uppercase'] },
  { id: 'Xi', category: 'greek', label: 'Xi', latex: '\\Xi', display: 'Ξ', keywords: ['Xi', 'greek', 'uppercase'] },
  { id: 'Pi', category: 'greek', label: 'Pi', latex: '\\Pi', display: 'Π', keywords: ['Pi', 'greek', 'uppercase'] },
  { id: 'Sigma', category: 'greek', label: 'Sigma', latex: '\\Sigma', display: 'Σ', keywords: ['Sigma', 'greek', 'uppercase'] },
  { id: 'Upsilon', category: 'greek', label: 'Upsilon', latex: '\\Upsilon', display: 'Υ', keywords: ['Upsilon', 'greek', 'uppercase'] },
  { id: 'Phi', category: 'greek', label: 'Phi', latex: '\\Phi', display: 'Φ', keywords: ['Phi', 'greek', 'uppercase'] },
  { id: 'Psi', category: 'greek', label: 'Psi', latex: '\\Psi', display: 'Ψ', keywords: ['Psi', 'greek', 'uppercase'] },
  { id: 'Omega', category: 'greek', label: 'Omega', latex: '\\Omega', display: 'Ω', keywords: ['Omega', 'greek', 'uppercase'] },

  // Operators
  { id: 'plus', category: 'operators', label: 'plus', latex: '+', display: '+', keywords: ['plus', 'add'] },
  { id: 'minus', category: 'operators', label: 'minus', latex: '-', display: '−', keywords: ['minus', 'subtract'] },
  { id: 'times', category: 'operators', label: 'times', latex: '\\times', display: '×', keywords: ['times', 'multiply', 'cross'] },
  { id: 'div', category: 'operators', label: 'div', latex: '\\div', display: '÷', keywords: ['div', 'divide'] },
  { id: 'pm', category: 'operators', label: 'plus-minus', latex: '\\pm', display: '±', keywords: ['pm', 'plus minus'] },
  { id: 'mp', category: 'operators', label: 'minus-plus', latex: '\\mp', display: '∓', keywords: ['mp', 'minus plus'] },
  { id: 'cdot', category: 'operators', label: 'cdot', latex: '\\cdot', display: '·', keywords: ['cdot', 'dot', 'multiply'] },
  { id: 'circ', category: 'operators', label: 'circ', latex: '\\circ', display: '∘', keywords: ['circ', 'compose', 'circle'] },
  { id: 'bullet', category: 'operators', label: 'bullet', latex: '\\bullet', display: '•', keywords: ['bullet', 'dot'] },
  { id: 'oplus', category: 'operators', label: 'oplus', latex: '\\oplus', display: '⊕', keywords: ['oplus', 'xor', 'direct sum'] },
  { id: 'ominus', category: 'operators', label: 'ominus', latex: '\\ominus', display: '⊖', keywords: ['ominus'] },
  { id: 'otimes', category: 'operators', label: 'otimes', latex: '\\otimes', display: '⊗', keywords: ['otimes', 'tensor'] },
  { id: 'oslash', category: 'operators', label: 'oslash', latex: '\\oslash', display: '⊘', keywords: ['oslash'] },
  { id: 'odot', category: 'operators', label: 'odot', latex: '\\odot', display: '⊙', keywords: ['odot'] },
  { id: 'cup', category: 'operators', label: 'cup (union)', latex: '\\cup', display: '∪', keywords: ['cup', 'union'] },
  { id: 'cap', category: 'operators', label: 'cap (intersection)', latex: '\\cap', display: '∩', keywords: ['cap', 'intersection'] },
  { id: 'wedge', category: 'operators', label: 'wedge (and)', latex: '\\wedge', display: '∧', keywords: ['wedge', 'and', 'logical'] },
  { id: 'vee', category: 'operators', label: 'vee (or)', latex: '\\vee', display: '∨', keywords: ['vee', 'or', 'logical'] },
  { id: 'setminus', category: 'operators', label: 'setminus', latex: '\\setminus', display: '∖', keywords: ['setminus', 'set difference'] },
  { id: 'star', category: 'operators', label: 'star', latex: '\\star', display: '⋆', keywords: ['star'] },
  { id: 'ast', category: 'operators', label: 'ast', latex: '\\ast', display: '∗', keywords: ['ast', 'asterisk'] },
  { id: 'amalg', category: 'operators', label: 'amalg', latex: '\\amalg', display: '∐', keywords: ['amalg', 'coproduct'] },
  { id: 'dagger', category: 'operators', label: 'dagger', latex: '\\dagger', display: '†', keywords: ['dagger', 'cross'] },
  { id: 'ddagger', category: 'operators', label: 'ddagger', latex: '\\ddagger', display: '‡', keywords: ['ddagger', 'double dagger'] },

  // Relations
  { id: 'eq', category: 'relations', label: 'equals', latex: '=', display: '=', keywords: ['eq', 'equals'] },
  { id: 'neq', category: 'relations', label: 'not equal', latex: '\\neq', display: '≠', keywords: ['neq', 'not equal'] },
  { id: 'lt', category: 'relations', label: 'less than', latex: '<', display: '<', keywords: ['lt', 'less than'] },
  { id: 'gt', category: 'relations', label: 'greater than', latex: '>', display: '>', keywords: ['gt', 'greater than'] },
  { id: 'leq', category: 'relations', label: 'less or equal', latex: '\\leq', display: '≤', keywords: ['leq', 'less equal'] },
  { id: 'geq', category: 'relations', label: 'greater or equal', latex: '\\geq', display: '≥', keywords: ['geq', 'greater equal'] },
  { id: 'approx', category: 'relations', label: 'approx', latex: '\\approx', display: '≈', keywords: ['approx', 'approximately equal'] },
  { id: 'equiv', category: 'relations', label: 'equiv', latex: '\\equiv', display: '≡', keywords: ['equiv', 'equivalent'] },
  { id: 'sim', category: 'relations', label: 'sim', latex: '\\sim', display: '∼', keywords: ['sim', 'similar'] },
  { id: 'simeq', category: 'relations', label: 'simeq', latex: '\\simeq', display: '≃', keywords: ['simeq', 'similar equal'] },
  { id: 'cong', category: 'relations', label: 'cong', latex: '\\cong', display: '≅', keywords: ['cong', 'congruent'] },
  { id: 'in', category: 'relations', label: 'in', latex: '\\in', display: '∈', keywords: ['in', 'element of', 'member'] },
  { id: 'notin', category: 'relations', label: 'not in', latex: '\\notin', display: '∉', keywords: ['notin', 'not in', 'not member'] },
  { id: 'ni', category: 'relations', label: 'contains', latex: '\\ni', display: '∋', keywords: ['ni', 'contains'] },
  { id: 'subset', category: 'relations', label: 'subset', latex: '\\subset', display: '⊂', keywords: ['subset'] },
  { id: 'supset', category: 'relations', label: 'supset', latex: '\\supset', display: '⊃', keywords: ['supset', 'superset'] },
  { id: 'subseteq', category: 'relations', label: 'subseteq', latex: '\\subseteq', display: '⊆', keywords: ['subseteq', 'subset equal'] },
  { id: 'supseteq', category: 'relations', label: 'supseteq', latex: '\\supseteq', display: '⊇', keywords: ['supseteq', 'superset equal'] },
  { id: 'parallel', category: 'relations', label: 'parallel', latex: '\\parallel', display: '∥', keywords: ['parallel'] },
  { id: 'perp', category: 'relations', label: 'perp', latex: '\\perp', display: '⊥', keywords: ['perp', 'perpendicular'] },
  { id: 'propto', category: 'relations', label: 'propto', latex: '\\propto', display: '∝', keywords: ['propto', 'proportional'] },
  { id: 'll', category: 'relations', label: 'much less', latex: '\\ll', display: '≪', keywords: ['ll', 'much less'] },
  { id: 'gg', category: 'relations', label: 'much greater', latex: '\\gg', display: '≫', keywords: ['gg', 'much greater'] },
  { id: 'mid', category: 'relations', label: 'mid', latex: '\\mid', display: '∣', keywords: ['mid', 'divides'] },
  { id: 'nmid', category: 'relations', label: 'nmid', latex: '\\nmid', display: '∤', keywords: ['nmid', 'does not divide'] },
  { id: 'asymp', category: 'relations', label: 'asymp', latex: '\\asymp', display: '≍', keywords: ['asymp', 'asymptotically equal'] },

  // Arrows
  { id: 'rightarrow', category: 'arrows', label: 'right arrow', latex: '\\rightarrow', display: '→', keywords: ['rightarrow', 'right', 'arrow', 'to'] },
  { id: 'leftarrow', category: 'arrows', label: 'left arrow', latex: '\\leftarrow', display: '←', keywords: ['leftarrow', 'left', 'arrow'] },
  { id: 'leftrightarrow', category: 'arrows', label: 'left-right arrow', latex: '\\leftrightarrow', display: '↔', keywords: ['leftrightarrow', 'both', 'arrow'] },
  { id: 'Rightarrow', category: 'arrows', label: 'implies', latex: '\\Rightarrow', display: '⇒', keywords: ['Rightarrow', 'implies', 'double right'] },
  { id: 'Leftarrow', category: 'arrows', label: 'implied by', latex: '\\Leftarrow', display: '⇐', keywords: ['Leftarrow', 'double left'] },
  { id: 'Leftrightarrow', category: 'arrows', label: 'iff', latex: '\\Leftrightarrow', display: '⇔', keywords: ['Leftrightarrow', 'iff', 'double both'] },
  { id: 'uparrow', category: 'arrows', label: 'up arrow', latex: '\\uparrow', display: '↑', keywords: ['uparrow', 'up'] },
  { id: 'downarrow', category: 'arrows', label: 'down arrow', latex: '\\downarrow', display: '↓', keywords: ['downarrow', 'down'] },
  { id: 'updownarrow', category: 'arrows', label: 'up-down arrow', latex: '\\updownarrow', display: '↕', keywords: ['updownarrow', 'up down'] },
  { id: 'nearrow', category: 'arrows', label: 'northeast arrow', latex: '\\nearrow', display: '↗', keywords: ['nearrow', 'northeast'] },
  { id: 'searrow', category: 'arrows', label: 'southeast arrow', latex: '\\searrow', display: '↘', keywords: ['searrow', 'southeast'] },
  { id: 'nwarrow', category: 'arrows', label: 'northwest arrow', latex: '\\nwarrow', display: '↖', keywords: ['nwarrow', 'northwest'] },
  { id: 'swarrow', category: 'arrows', label: 'southwest arrow', latex: '\\swarrow', display: '↙', keywords: ['swarrow', 'southwest'] },
  { id: 'mapsto', category: 'arrows', label: 'mapsto', latex: '\\mapsto', display: '↦', keywords: ['mapsto', 'maps to'] },
  { id: 'hookrightarrow', category: 'arrows', label: 'hookrightarrow', latex: '\\hookrightarrow', display: '↪', keywords: ['hookrightarrow', 'injection'] },
  { id: 'hookleftarrow', category: 'arrows', label: 'hookleftarrow', latex: '\\hookleftarrow', display: '↩', keywords: ['hookleftarrow'] },
  { id: 'longrightarrow', category: 'arrows', label: 'long right arrow', latex: '\\longrightarrow', display: '⟶', keywords: ['longrightarrow', 'long right'] },
  { id: 'longleftarrow', category: 'arrows', label: 'long left arrow', latex: '\\longleftarrow', display: '⟵', keywords: ['longleftarrow', 'long left'] },
  { id: 'Longrightarrow', category: 'arrows', label: 'long implies', latex: '\\Longrightarrow', display: '⟹', keywords: ['Longrightarrow', 'long implies'] },
  { id: 'Longleftrightarrow', category: 'arrows', label: 'long iff', latex: '\\Longleftrightarrow', display: '⟺', keywords: ['Longleftrightarrow', 'long iff'] },
  { id: 'rightharpoonup', category: 'arrows', label: 'rightharpoonup', latex: '\\rightharpoonup', display: '⇀', keywords: ['rightharpoonup', 'harpoon'] },
  { id: 'rightharpoondown', category: 'arrows', label: 'rightharpoondown', latex: '\\rightharpoondown', display: '⇁', keywords: ['rightharpoondown', 'harpoon'] },

  // Structures
  { id: 'frac', category: 'structures', label: 'fraction', latex: '\\frac{a}{b}', display: '¼', keywords: ['frac', 'fraction', 'divide'] },
  { id: 'sqrt', category: 'structures', label: 'square root', latex: '\\sqrt{x}', display: '√', keywords: ['sqrt', 'square root', 'radical'] },
  { id: 'sum', category: 'structures', label: 'sum', latex: '\\sum_{i=1}^{n}', display: '∑', keywords: ['sum', 'summation', 'sigma'] },
  { id: 'int', category: 'structures', label: 'integral', latex: '\\int_{a}^{b}', display: '∫', keywords: ['int', 'integral'] },
  { id: 'iint', category: 'structures', label: 'double integral', latex: '\\iint', display: '∬', keywords: ['iint', 'double integral'] },
  { id: 'iiint', category: 'structures', label: 'triple integral', latex: '\\iiint', display: '∭', keywords: ['iiint', 'triple integral'] },
  { id: 'oint', category: 'structures', label: 'contour integral', latex: '\\oint', display: '∮', keywords: ['oint', 'contour integral'] },
  { id: 'prod', category: 'structures', label: 'product', latex: '\\prod_{i=1}^{n}', display: '∏', keywords: ['prod', 'product'] },
  { id: 'lim', category: 'structures', label: 'limit', latex: '\\lim_{x \\to \\infty}', display: 'lim', keywords: ['lim', 'limit'] },
  { id: 'partial', category: 'structures', label: 'partial', latex: '\\partial', display: '∂', keywords: ['partial', 'derivative'] },
  { id: 'nabla', category: 'structures', label: 'nabla', latex: '\\nabla', display: '∇', keywords: ['nabla', 'gradient', 'del'] },
  { id: 'overline', category: 'structures', label: 'overline', latex: '\\overline{x}', display: 'x̄', keywords: ['overline', 'bar'] },
  { id: 'underline', category: 'structures', label: 'underline', latex: '\\underline{x}', display: 'x̲', keywords: ['underline'] },
  { id: 'hat', category: 'structures', label: 'hat', latex: '\\hat{x}', display: 'x̂', keywords: ['hat', 'caret'] },
  { id: 'vec', category: 'structures', label: 'vec', latex: '\\vec{x}', display: 'x⃗', keywords: ['vec', 'vector', 'arrow over'] },
  { id: 'dot', category: 'structures', label: 'dot', latex: '\\dot{x}', display: 'ẋ', keywords: ['dot', 'derivative'] },
  { id: 'ddot', category: 'structures', label: 'ddot', latex: '\\ddot{x}', display: 'ẍ', keywords: ['ddot', 'double dot', 'second derivative'] },
  { id: 'tilde', category: 'structures', label: 'tilde', latex: '\\tilde{x}', display: 'x̃', keywords: ['tilde'] },
  { id: 'widehat', category: 'structures', label: 'widehat', latex: '\\widehat{xy}', display: 'x̂', keywords: ['widehat', 'wide hat'] },
  { id: 'widetilde', category: 'structures', label: 'widetilde', latex: '\\widetilde{xy}', display: 'x̃', keywords: ['widetilde', 'wide tilde'] },
  { id: 'overbrace', category: 'structures', label: 'overbrace', latex: '\\overbrace{a+b}^{n}', display: '⏞', keywords: ['overbrace'] },
  { id: 'underbrace', category: 'structures', label: 'underbrace', latex: '\\underbrace{a+b}_{n}', display: '⏟', keywords: ['underbrace'] },
  { id: 'sqrt3', category: 'structures', label: 'nth root', latex: '\\sqrt[n]{x}', display: '∛', keywords: ['sqrt', 'nth root', 'cube root'] },
  { id: 'binom', category: 'structures', label: 'binomial', latex: '\\binom{n}{k}', display: 'C', keywords: ['binom', 'binomial', 'choose'] },
  { id: 'matrix', category: 'structures', label: 'matrix', latex: '\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix}', display: '▦', keywords: ['matrix', 'pmatrix'] },
  { id: 'cases', category: 'structures', label: 'cases', latex: '\\begin{cases} a & x>0 \\\\ b & x\\leq 0 \\end{cases}', display: '{', keywords: ['cases', 'piecewise'] },
  { id: 'inf', category: 'structures', label: 'infty', latex: '\\infty', display: '∞', keywords: ['infty', 'infinity'] },

  // Accents
  { id: 'acute', category: 'accents', label: 'acute', latex: "\\acute{x}", display: 'x́', keywords: ['acute', 'accent'] },
  { id: 'grave', category: 'accents', label: 'grave', latex: '\\grave{x}', display: 'x̀', keywords: ['grave', 'accent'] },
  { id: 'check', category: 'accents', label: 'check', latex: '\\check{x}', display: 'x̌', keywords: ['check', 'caron', 'accent'] },
  { id: 'breve', category: 'accents', label: 'breve', latex: '\\breve{x}', display: 'x̆', keywords: ['breve', 'accent'] },
  { id: 'bar', category: 'accents', label: 'bar', latex: '\\bar{x}', display: 'x̄', keywords: ['bar', 'accent'] },
  { id: 'hat_accent', category: 'accents', label: 'hat accent', latex: '\\hat{x}', display: 'x̂', keywords: ['hat', 'caret', 'accent'] },
  { id: 'tilde_accent', category: 'accents', label: 'tilde accent', latex: '\\tilde{x}', display: 'x̃', keywords: ['tilde', 'accent'] },
  { id: 'dot_accent', category: 'accents', label: 'dot accent', latex: '\\dot{x}', display: 'ẋ', keywords: ['dot', 'accent'] },
  { id: 'ddot_accent', category: 'accents', label: 'ddot accent', latex: '\\ddot{x}', display: 'ẍ', keywords: ['ddot', 'umlaut', 'accent'] },
  { id: 'vec_accent', category: 'accents', label: 'vec accent', latex: '\\vec{x}', display: 'x⃗', keywords: ['vec', 'vector', 'accent'] },
  { id: 'ring', category: 'accents', label: 'ring', latex: '\\mathring{x}', display: 'x̊', keywords: ['ring', 'circle', 'accent'] },
  { id: 'not', category: 'accents', label: 'not (slash)', latex: '\\not{=}', display: '≠', keywords: ['not', 'negation', 'slash'] },

  // Delimiters
  { id: 'lparen', category: 'delimiters', label: 'left paren', latex: '(', display: '(', keywords: ['lparen', 'left paren', 'open'] },
  { id: 'rparen', category: 'delimiters', label: 'right paren', latex: ')', display: ')', keywords: ['rparen', 'right paren', 'close'] },
  { id: 'lbracket', category: 'delimiters', label: 'left bracket', latex: '[', display: '[', keywords: ['lbracket', 'left bracket', 'open'] },
  { id: 'rbracket', category: 'delimiters', label: 'right bracket', latex: ']', display: ']', keywords: ['rbracket', 'right bracket', 'close'] },
  { id: 'lbrace', category: 'delimiters', label: 'left brace', latex: '\\{', display: '{', keywords: ['lbrace', 'left brace', 'curly'] },
  { id: 'rbrace', category: 'delimiters', label: 'right brace', latex: '\\}', display: '}', keywords: ['rbrace', 'right brace', 'curly'] },
  { id: 'langle', category: 'delimiters', label: 'left angle', latex: '\\langle', display: '⟨', keywords: ['langle', 'left angle', 'bracket'] },
  { id: 'rangle', category: 'delimiters', label: 'right angle', latex: '\\rangle', display: '⟩', keywords: ['rangle', 'right angle', 'bracket'] },
  { id: 'lceil', category: 'delimiters', label: 'left ceil', latex: '\\lceil', display: '⌈', keywords: ['lceil', 'ceiling', 'left'] },
  { id: 'rceil', category: 'delimiters', label: 'right ceil', latex: '\\rceil', display: '⌉', keywords: ['rceil', 'ceiling', 'right'] },
  { id: 'lfloor', category: 'delimiters', label: 'left floor', latex: '\\lfloor', display: '⌊', keywords: ['lfloor', 'floor', 'left'] },
  { id: 'rfloor', category: 'delimiters', label: 'right floor', latex: '\\rfloor', display: '⌋', keywords: ['rfloor', 'floor', 'right'] },
  { id: 'vert', category: 'delimiters', label: 'vert', latex: '\\vert', display: '|', keywords: ['vert', 'absolute value', 'pipe'] },
  { id: 'Vert', category: 'delimiters', label: 'Vert', latex: '\\Vert', display: '‖', keywords: ['Vert', 'norm', 'double pipe'] },
  { id: 'lVert', category: 'delimiters', label: 'lVert', latex: '\\lVert', display: '‖', keywords: ['lVert', 'norm', 'left'] },
  { id: 'rVert', category: 'delimiters', label: 'rVert', latex: '\\rVert', display: '‖', keywords: ['rVert', 'norm', 'right'] },
  { id: 'bigl', category: 'delimiters', label: 'big left paren', latex: '\\bigl(', display: '(', keywords: ['bigl', 'big', 'paren'] },
  { id: 'bigr', category: 'delimiters', label: 'big right paren', latex: '\\bigr)', display: ')', keywords: ['bigr', 'big', 'paren'] },
  { id: 'left_right', category: 'delimiters', label: 'auto-size parens', latex: '\\left( x \\right)', display: '( )', keywords: ['left', 'right', 'auto size'] },

  // Misc
  { id: 'infty', category: 'misc', label: 'infinity', latex: '\\infty', display: '∞', keywords: ['infty', 'infinity'] },
  { id: 'emptyset', category: 'misc', label: 'empty set', latex: '\\emptyset', display: '∅', keywords: ['emptyset', 'empty', 'null set'] },
  { id: 'forall', category: 'misc', label: 'for all', latex: '\\forall', display: '∀', keywords: ['forall', 'for all', 'universal'] },
  { id: 'exists', category: 'misc', label: 'exists', latex: '\\exists', display: '∃', keywords: ['exists', 'there exists', 'existential'] },
  { id: 'nexists', category: 'misc', label: 'nexists', latex: '\\nexists', display: '∄', keywords: ['nexists', 'does not exist'] },
  { id: 'aleph', category: 'misc', label: 'aleph', latex: '\\aleph', display: 'ℵ', keywords: ['aleph', 'cardinal'] },
  { id: 'hbar', category: 'misc', label: 'hbar', latex: '\\hbar', display: 'ℏ', keywords: ['hbar', 'planck', 'physics'] },
  { id: 'ell', category: 'misc', label: 'ell', latex: '\\ell', display: 'ℓ', keywords: ['ell', 'script l'] },
  { id: 'Re', category: 'misc', label: 'Real part', latex: '\\Re', display: 'ℜ', keywords: ['Re', 'real part', 'complex'] },
  { id: 'Im', category: 'misc', label: 'Imaginary part', latex: '\\Im', display: 'ℑ', keywords: ['Im', 'imaginary part', 'complex'] },
  { id: 'top', category: 'misc', label: 'top', latex: '\\top', display: '⊤', keywords: ['top', 'true', 'tautology'] },
  { id: 'bot', category: 'misc', label: 'bot', latex: '\\bot', display: '⊥', keywords: ['bot', 'false', 'contradiction'] },
  { id: 'angle', category: 'misc', label: 'angle', latex: '\\angle', display: '∠', keywords: ['angle', 'geometry'] },
  { id: 'triangle', category: 'misc', label: 'triangle', latex: '\\triangle', display: '△', keywords: ['triangle', 'geometry'] },
  { id: 'square', category: 'misc', label: 'square', latex: '\\square', display: '□', keywords: ['square', 'box', 'qed'] },
  { id: 'diamond', category: 'misc', label: 'diamond', latex: '\\diamond', display: '⋄', keywords: ['diamond'] },
  { id: 'clubsuit', category: 'misc', label: 'clubsuit', latex: '\\clubsuit', display: '♣', keywords: ['clubsuit', 'club'] },
  { id: 'heartsuit', category: 'misc', label: 'heartsuit', latex: '\\heartsuit', display: '♡', keywords: ['heartsuit', 'heart'] },
  { id: 'spadesuit', category: 'misc', label: 'spadesuit', latex: '\\spadesuit', display: '♠', keywords: ['spadesuit', 'spade'] },
  { id: 'diamondsuit', category: 'misc', label: 'diamondsuit', latex: '\\diamondsuit', display: '♢', keywords: ['diamondsuit', 'diamond'] },
  { id: 'cdots', category: 'misc', label: 'cdots', latex: '\\cdots', display: '⋯', keywords: ['cdots', 'center dots', 'ellipsis'] },
  { id: 'ldots', category: 'misc', label: 'ldots', latex: '\\ldots', display: '…', keywords: ['ldots', 'dots', 'ellipsis'] },
  { id: 'vdots', category: 'misc', label: 'vdots', latex: '\\vdots', display: '⋮', keywords: ['vdots', 'vertical dots'] },
  { id: 'ddots', category: 'misc', label: 'ddots', latex: '\\ddots', display: '⋱', keywords: ['ddots', 'diagonal dots'] },
  { id: 'prime', category: 'misc', label: 'prime', latex: '\\prime', display: '′', keywords: ['prime', 'derivative'] },
  { id: 'backslash', category: 'misc', label: 'backslash', latex: '\\backslash', display: '\\', keywords: ['backslash'] },
  { id: 'wp', category: 'misc', label: 'Weierstrass p', latex: '\\wp', display: '℘', keywords: ['wp', 'weierstrass', 'script p'] },
  { id: 'surd', category: 'misc', label: 'surd', latex: '\\surd', display: '√', keywords: ['surd', 'radical', 'root'] },
  { id: 'sharp', category: 'misc', label: 'sharp', latex: '\\sharp', display: '♯', keywords: ['sharp', 'music'] },
  { id: 'flat', category: 'misc', label: 'flat', latex: '\\flat', display: '♭', keywords: ['flat', 'music'] },
  { id: 'natural', category: 'misc', label: 'natural', latex: '\\natural', display: '♮', keywords: ['natural', 'music'] },
];
